<script lang="ts">
  import Seo from '$lib/components/Seo.svelte';
  import ServiceCards from '$lib/components/ServiceCards.svelte';
  import Cta from '$lib/components/Cta.svelte';
</script>
<Seo title="Mer oversikt. Mer handlingsrom." />
<section class="wrap grid items-center gap-12 py-16 lg:grid-cols-[1.1fr_1fr] lg:gap-16 lg:py-24">
  <div><p class="eyebrow mb-7 flex items-center gap-3"><span class="h-2 w-2 rounded-full bg-[#718341]"></span> Din neste regnskapspartner</p><h1 class="text-5xl font-medium leading-[1.06] tracking-[-0.055em] sm:text-6xl xl:text-7xl">Trygg på tallene.<br /><span class="text-[#718341]">Fri til å skape.</span></h1><p class="mt-7 max-w-lg text-lg leading-relaxed text-muted">Du bygger bedriften. Vi hjelper deg med oversikten. Regnskap, lønn og rådgivning — forklart så det gir mening.</p><div class="mt-9 flex flex-wrap items-center gap-7"><a class="button" href="/kontakt/">La oss ta en prat <span aria-hidden="true">↗</span></a><a class="text-sm font-semibold underline underline-offset-8" href="/tjenester/">Utforsk tjenestene</a></div><p class="mt-10 text-xs text-muted">Personlig oppfølging <span class="mx-3" aria-hidden="true">/</span> Digitale arbeidsmåter</p></div>
  <div class="relative overflow-hidden rounded-[2rem] bg-[#e8ebdf] p-7 sm:p-10" aria-label="Illustrasjon av en ryddig økonomihverdag">
    <div class="flex items-center justify-between text-xs"><span class="eyebrow">Litt mer oversikt</span><span class="rounded-full bg-white/70 px-3 py-2">Illustrasjon</span></div>
    <div class="mb-8 mt-10 rounded-2xl bg-paper p-6 shadow-[0_20px_60px_-30px_#193d3555]"><div class="flex justify-between"><span class="text-sm text-muted">Din økonomihverdag</span><span aria-hidden="true">↗</span></div><p class="mt-4 text-3xl font-medium tracking-tight">Alt på ett sted.</p><div class="mt-8 flex h-28 items-end gap-3" aria-hidden="true">{#each [35, 52, 44, 70, 62, 84, 100] as height, index}<div style={`height: ${height}%`} class={`flex-1 rounded-t-md ${index === 6 ? 'bg-[#718341]' : 'bg-ink/15'}`}></div>{/each}</div><p class="mt-4 border-t border-ink/10 pt-4 text-xs text-muted">Oversikt som gir rom for gode beslutninger.</p></div>
    <div class="ml-5 rounded-xl bg-ink p-5 text-paper"><span class="text-lime" aria-hidden="true">✓</span><span class="ml-3 text-sm">Mindre å holde styr på. Mer å se frem til.</span></div>
  </div>
</section>
<div class="border-y border-ink/15"><div class="wrap grid gap-5 py-6 text-sm sm:grid-cols-3"><p>01 <span class="ml-4">En fast samtalepartner</span></p><p>02 <span class="ml-4">Oversikt i hverdagen</span></p><p>03 <span class="ml-4">Plass til å vokse</span></p></div></div>
<section class="wrap py-20"><div class="mb-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p class="eyebrow mb-5">Dette kan vi hjelpe med</p><h2 class="heading">God økonomi begynner<br />med god oversikt.</h2></div><a href="/tjenester/" class="text-sm font-semibold underline underline-offset-8">Alle tjenester ↗</a></div><ServiceCards /></section>
<section class="bg-[#e8ebdf] py-20"><div class="wrap grid gap-10 lg:grid-cols-2"><p class="eyebrow">Nært samarbeid. Enklere hverdag.</p><div><h2 class="heading">En partner du kan<br />snakke med.</h2><p class="mt-7 max-w-xl text-lg leading-relaxed text-muted">Økonomi skal være forståelig. Vi tror på tydelige svar, god dialog og løsninger som passer hverdagen din — enten du er i startfasen eller klar for neste steg.</p><a href="/om-oss/" class="mt-8 inline-block text-sm font-semibold underline underline-offset-8">Bli kjent med oss ↗</a></div></div></section>
<section class="wrap py-20"><p class="eyebrow mb-5">Slik kommer vi i gang</p><h2 class="heading mb-12">En enkel start.</h2><div class="grid gap-9 md:grid-cols-3">{#each [{title:'Vi blir kjent',text:'Fortell oss om bedriften din, hverdagen og hva du trenger hjelp med.'},{title:'Vi finner en god løsning',text:'Sammen avklarer vi omfang, arbeidsmåter og forventninger.'},{title:'Vi følger deg opp',text:'Vi etablerer faste rutiner og holder dialogen åpen underveis.'}] as step, i}<div class="border-t border-ink/25 pt-5"><span class="eyebrow text-muted">0{i + 1}</span><h3 class="mb-3 mt-6 text-xl font-medium">{step.title}</h3><p class="leading-relaxed text-muted">{step.text}</p></div>{/each}</div></section><Cta />
