<script lang="ts">
  import Seo from '$lib/components/Seo.svelte';
  import ServiceCards from '$lib/components/ServiceCards.svelte';
  import Cta from '$lib/components/Cta.svelte';
</script>
<Seo title="Mer oversikt. Mer handlingsrom." />
<section class="wrap grid items-center gap-12 py-16 lg:grid-cols-[1.1fr_1fr] lg:gap-16 lg:py-24">
  <div><p class="eyebrow mb-7 flex items-center gap-3"><span class="h-2 w-2 rounded-full bg-[#718341]"></span> Din neste regnskapspartner</p><h1 class="text-5xl font-medium leading-[1.06] tracking-[-0.055em] sm:text-6xl xl:text-7xl">Trygg på tallene.<br /><span class="text-[#718341]">Fri til å skape.</span></h1><p class="mt-7 max-w-lg text-lg leading-relaxed text-muted">Du bygger bedriften. Vi hjelper deg med oversikten. Regnskap, lønn og rådgivning — forklart så det gir mening.</p><div class="mt-9 flex flex-wrap items-center gap-7"><a class="button" href="/kontakt/">La oss ta en prat <span aria-hidden="true">↗</span></a><a class="text-sm font-semibold underline underline-offset-8" href="/tjenester/">Utforsk tjenestene</a></div><p class="mt-10 text-xs text-muted">Personlig oppfølging <span class="mx-3" aria-hidden="true">/</span> Digitale arbeidsmåter</p></div>
  <figure class="relative isolate overflow-hidden rounded-[2rem] bg-[#e8ebdf]">
    <img src="/images/client-meeting-1120.webp" srcset="/images/client-meeting-640.webp 640w, /images/client-meeting-1120.webp 1120w" sizes="(min-width: 1280px) 492px, (min-width: 1024px) 44vw, calc(100vw - 48px)" width="1120" height="1400" alt="To personer gjennomgår dokumenter sammen ved et lyst trebord. KI-generert illustrasjonsfoto." fetchpriority="high" class="aspect-[4/5] max-h-[620px] w-full object-cover" />
    <div class="pointer-events-none absolute inset-0 bg-gradient-to-t from-ink/70 via-transparent to-transparent" aria-hidden="true"></div>
    <figcaption class="absolute inset-x-5 bottom-5 rounded-2xl border border-white/30 bg-paper/95 p-5 backdrop-blur-sm sm:inset-x-7 sm:bottom-7 sm:p-6">
      <p class="eyebrow mb-3 text-muted">Mennesker bak tallene</p>
      <p class="text-xl font-medium tracking-tight sm:text-2xl">God oversikt starter<br />med en god samtale.</p>
      <a href="/om-oss/" class="mt-4 inline-flex items-center gap-5 text-sm font-semibold underline-offset-4 hover:underline">Bli kjent med oss <span aria-hidden="true">↗</span></a>
    </figcaption>
  </figure>
</section>
<div class="border-y border-ink/15"><div class="wrap grid gap-5 py-6 text-sm sm:grid-cols-3"><p>01 <span class="ml-4">En fast samtalepartner</span></p><p>02 <span class="ml-4">Oversikt i hverdagen</span></p><p>03 <span class="ml-4">Plass til å vokse</span></p></div></div>
<section class="wrap py-20"><div class="mb-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p class="eyebrow mb-5">Dette kan vi hjelpe med</p><h2 class="heading">God økonomi begynner<br />med god oversikt.</h2></div><a href="/tjenester/" class="text-sm font-semibold underline underline-offset-8">Alle tjenester ↗</a></div><ServiceCards /></section>
<section class="bg-[#e8ebdf] py-20"><div class="wrap grid items-center gap-10 lg:grid-cols-2"><figure><img src="/images/stock-partner-1120.webp" srcset="/images/stock-partner-640.webp 640w, /images/stock-partner-1120.webp 1120w" sizes="(min-width: 1280px) 556px, (min-width: 1024px) 45vw, calc(100vw - 48px)" width="1120" height="1679" alt="Kollegaer samarbeider om dokumenter ved en bærbar datamaskin. Illustrasjonsfoto." loading="lazy" decoding="async" class="aspect-[4/3] w-full rounded-3xl object-cover" /></figure><div><p class="eyebrow mb-6">Nært samarbeid. Enklere hverdag.</p><h2 class="heading">En partner du kan<br />snakke med.</h2><p class="mt-7 max-w-xl text-lg leading-relaxed text-muted">Økonomi skal være forståelig. Vi tror på tydelige svar, god dialog og løsninger som passer hverdagen din — enten du er i startfasen eller klar for neste steg.</p><a href="/om-oss/" class="mt-8 inline-block text-sm font-semibold underline underline-offset-8">Bli kjent med oss ↗</a></div></div></section>
<section class="wrap py-20"><p class="eyebrow mb-5">Slik kommer vi i gang</p><h2 class="heading mb-12">En enkel start.</h2><div class="grid gap-9 md:grid-cols-3">{#each [{title:'Vi blir kjent',text:'Fortell oss om bedriften din, hverdagen og hva du trenger hjelp med.'},{title:'Vi finner en god løsning',text:'Sammen avklarer vi omfang, arbeidsmåter og forventninger.'},{title:'Vi følger deg opp',text:'Vi etablerer faste rutiner og holder dialogen åpen underveis.'}] as step, i}<div class="border-t border-ink/25 pt-5"><span class="eyebrow text-muted">0{i + 1}</span><h3 class="mb-3 mt-6 text-xl font-medium">{step.title}</h3><p class="leading-relaxed text-muted">{step.text}</p></div>{/each}</div></section><Cta />
