<script lang="ts">
  import { onMount } from 'svelte';
  let ready = $state(false);
  onMount(() => { ready = true; });
  import Seo from '$lib/components/Seo.svelte';
  let submitted = $state(false);
  function submit(event: SubmitEvent) { event.preventDefault(); submitted = true; }
</script>
<Seo title="Kontakt" />
<section class="wrap grid gap-12 py-16 lg:grid-cols-2 lg:gap-20 sm:py-24"><div><p class="eyebrow mb-6">La oss bli kjent</p><h1 class="heading">Hva kan vi<br />hjelpe deg med?</h1><p class="mt-7 max-w-md text-lg leading-relaxed text-muted">Fortell litt om bedriften din og hva du ønsker hjelp med. En god samtale er et fint sted å starte.</p><figure class="mt-8"><img src="/images/stock-contact-1120.webp" srcset="/images/stock-contact-640.webp 640w, /images/stock-contact-1120.webp 1120w" sizes="(min-width: 1280px) 556px, (min-width: 1024px) 45vw, calc(100vw - 48px)" width="1120" height="805" alt="En åpen notatbok, penn og kaffekopp ved siden av en datamaskin." loading="lazy" decoding="async" class="aspect-[16/9] w-full rounded-3xl object-cover" /></figure><div class="mt-8 rounded-2xl bg-lime p-6"><h2 class="font-semibold">Dette er et demoskjema</h2><p class="mt-3 text-sm leading-relaxed">Ingen opplysninger sendes eller lagres. Bruk fiktive opplysninger for å prøve skjemaet. Ekte kontaktinformasjon og skjematjeneste legges til ved kundetilpasning.</p></div></div>
<form onsubmit={submit} class="rounded-3xl border border-ink/15 bg-white/60 p-6 sm:p-9"><div class="grid gap-6"><label class="text-sm font-medium">Navn <span aria-hidden="true">*</span><input class="field" name="name" autocomplete="off" required maxlength="100" /></label><label class="text-sm font-medium">E-post <span aria-hidden="true">*</span><input class="field" name="email" type="email" autocomplete="off" required maxlength="254" /></label><label class="text-sm font-medium">Bedrift<input class="field" name="company" autocomplete="off" maxlength="150" /></label><label class="text-sm font-medium">Hva trenger du hjelp med?<select class="field" name="service"><option>Jeg ønsker en uforpliktende prat</option><option>Regnskap</option><option>Lønn og personal</option><option>Økonomisk rådgivning</option></select></label><label class="text-sm font-medium">Melding <span aria-hidden="true">*</span><textarea class="field min-h-32" name="message" required maxlength="3000"></textarea></label><p class="text-xs text-muted">* Obligatoriske felt. Kun fiktive opplysninger i denne demoen.</p><button class="button w-full disabled:cursor-not-allowed disabled:opacity-50" type="submit" disabled={!ready}>Prøv demoskjemaet <span aria-hidden="true">↗</span></button><div role="status" aria-live="polite">{#if submitted}<p class="rounded-xl bg-lime p-4 text-sm">Demo fullført. Ingenting er sendt eller lagret.</p>{/if}</div></div></form></section>
